name: commodity monitor

on:
  push:
    branches:
      - master
  schedule:
    - cron: '14 18,8 * * MON,TUE,WED,THU,FRI'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install -g pnpm
        pnpm install
        make commodity-monitor
    - name: Get current date
      id: date
      run: echo "current_date=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT
    - name: git
      run: |
        git status
        git config --global user.email "alfierichou@gmail.com"
        git config --global user.name "AlfieriChou"
        git add .
        git commit -m "chore: commodity monitor ${{ steps.date.outputs.current_date }} update"
        git push